name: Gitglue
description: Submit new input
title: "[Gitglue]: "
labels: ["Gitglue"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the below form
  - type: input
    id: idname
    attributes:
      label: Name
      description: Define the name of your VM
      placeholder: host-web-serv
    validations:
      required: true
  - type: dropdown
    id: idmemory
    attributes:
      label: Memory
      description: How much memory does your VM need?
      options:
        - 4GB
        - 8GB
    validations:
      required: true
  - type: checkboxes
    id: idnetworkpublic
    attributes:
      label: NetworkPublic
      description: Do you require public network access
      options:
        - label: I require public network access
          required: false
  - type: checkboxes
    id: idnetworkfireall
    attributes:
      label: NetworkFirewall
      description: Do you require public network access
      options:
        - label: I require a firewall
          required: false
        - label: I require a nat gateway
          required: false 
  - type: textarea
    id: iddescription
    attributes:
      label: Description
      description: Please provide a description
      placeholder: ...
    validations:
      required: true
