name: Gitty
description: Submit new input
title: "[Gitty]: "
labels: ["gitty"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the below form
  - type: input
    id: idname
    attributes:
      label: LabelName
      description: Define the name of your VM
      placeholder: host-web-serv
    validations:
      required: true
  - type: dropdown
    id: idmemory
    attributes:
      label: LabelMemory
      description: How much memory does your VM need?
      options:
        - 4GB
        - 8GB
    validations:
      required: true
  - type: checkboxes
    id: idnetworkpublic
    attributes:
      label: LabelNetworkPublic
      description: Do you require public network access
      options:
        - label: I require public network access
          required: false
   - type: checkboxes
    id: idnetworkfireall
    attributes:
      label: LabelNetworkFirewall
      description: Do you require public network access
      options:
        - label: I require a firewall
          required: false
