name: "Commit workflow"
on: 
  issues:
    types: [opened]

jobs:
  build:
    name: Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: npm install
      - uses: ./.github/actions/commit-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: commit
